<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FocusBar</AssemblyName>
    <RootNamespace>FocusBar</RootNamespace>
    <ApplicationIcon>icon.ico</ApplicationIcon>  
  </PropertyGroup>

  <ItemGroup>
    <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
	<Resource Include="icon.ico" />
  </ItemGroup>

</Project>
